### ISSUE TITLE
sliced模式下GetAdjustedBorders()函数需要修改

### ISSUE THREAD

**Issue by lyback** [L-Lawliet/UGUIExtend#1]
protected Vector4 GetAdjustedBorders(Rect rect)
        {
            Sprite overrideSprite = (graphic as Image).overrideSprite;

            Vector4 border = overrideSprite.border;

            border = (border / (graphic as Image).pixelsPerUnit)*2;//此处有修改

            for (int axis = 0; axis <= 1; axis++)
            {
                float combinedBorders = border[axis] + border[axis + 2];
                if (rect.size[axis] < combinedBorders && combinedBorders != 0)
                {
                    float borderScaleRatio = rect.size[axis] / combinedBorders;
                    border[axis] *= borderScaleRatio;
                    border[axis + 2] *= borderScaleRatio;
                }
            }

            return border;
        }

**Comment by L-Lawliet** [comment]
请问下，这里为什么要乘2呢？

**Comment by lyback** [comment]
不好意思，之前没认真看代码。
是我发现原来的代码在sliced模式下把图片压缩到很小的时候显示会出错，我之前用重写image的方法也出现过这个问题，我是因为这里border的范围没有扩大，因为我是将图片放大再镜像；
认真看了下您的代码，应该是缩小再镜像，所以改上面是没用的。
然后我改了下SlicedScale()这个函数，应该是没问题了。
[Mirror.zip](https://github.com/L-Lawliet/UGUIExtend/files/1377649/Mirror.zip)

**Comment by L-Lawliet** [comment]
嗯，因为GetAdjustedBorders这个函数的逻辑是直接拿的UGUI源码的。所以我有些疑惑这里乘上2的含义。
然后你说的把图片压缩到很小会出错，方便具体说说是用了什么缩小吗？（改变Image的Width/Height？还是其他压缩大小？）

**Comment by lyback** [comment]
用Width/Height缩小的,准确的说应该是当border的范围缩小到0时会出错
![default](https://user-images.githubusercontent.com/16044015/31537627-6568bb20-b035-11e7-902d-c962aeb69feb.png)

**Comment by lyback** [comment]
修改了下SlicedScale()函数里逻辑判断的边界值
[Mirror.txt](https://github.com/L-Lawliet/UGUIExtend/files/1382047/Mirror.txt)

**Comment by L-Lawliet** [comment]
我找到你说的bug了，就是Sprite的border是0的情况下，绘制Sliced出错的。
由于UGUI在这种情况，Sliced的模式会变成Simple绘制，所以Mirror也是按照Simple来绘制。
可是由于我的疏忽，少打了一个return。所以导致绘制出错。
现在已经修复完了，这个bug。
#### 最后很感谢你帮忙找出来和修复。
